import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

import { useRouter, Link } from "nextjs-i18n-router";

export default function Home() {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js I18n Router</a>
          </h1>
        </div>

        <p className={styles.description}>
          Current route information:
          <br />
          <code className={styles.code}>Locale: {router.locale}</code>{" "}
          <code className={styles.code}>As: {router.asPath}</code>
          <br />
          <code className={styles.code}>Pathname: {router.pathname}</code>{" "}
          <code className={styles.code}>
            Query: {JSON.stringify(router.query)}
          </code>
        </p>

        <div className={styles.grid}>
          <Link name="home" params={{ slug: ["slug-1", "slug-2"] }} passHref>
            <a className={styles.card}>
              <h2>`home` &rarr;</h2>
              <p>Go `home` route.</p>
            </a>
          </Link>
          <Link name="category" params={{ slug: "slug-1" }} passHref>
            <a className={styles.card}>
              <h2>`category` &rarr;</h2>
              <p>Go `category` route with one param.</p>
            </a>
          </Link>
          <Link
            name="category"
            params={{ slug: ["slug-1", "slug-2"] }}
            passHref
          >
            <a className={styles.card}>
              <h2>`category` &rarr;</h2>
              <p>Go `category` route with two param.</p>
            </a>
          </Link>
          <Link
            name="category"
            params={{ slug: ["slug-1", "slug-2", "slug-3"] }}
            passHref
          >
            <a className={styles.card}>
              <h2>`category` &rarr;</h2>
              <p>Go `category` route with three param.</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
